### PR TITLE
Replace UI screenshots

### LINKED ISSUE #82: [PE-D][Tester C] UI does not match the first screenshot in the UG
-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: lshaoqin/ped#1

### LINKED ISSUE #98: [PE-D][Tester C] List screenshot is not accurate
This is the outcome when I run `list` - fields like phone number and address do not appear like in the screenshot.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: lshaoqin/ped#7

### LINKED ISSUE #119: [PE-D][Tester A] outdated image
Your app UI is different from UG `list`.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: DonovanJJ/ped#6

### LINKED ISSUE #120: [PE-D][Tester B] GUI displayed in user guide does not match the actual GUI
The GUI displayed in the user guide seems quite different from the actual GUI of the application. It might be better to show the actual GUI and annatate to introduce users to the gui.

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: feifeiraindrops/ped#8

### PR DESCRIPTION
**Pull request by SungMatt**
Replaced UI screenshots for both the help window, and the general UI.
Fixes #120 (GUI display in Readme and UG do not match the actual GUI)
Fixes #119 (List image is outdated)
Fixes #98 (List image is outdated)
Fixes #82 (GUI display in ReadMe and UG do not match the actual GUI)

### CODE REVIEW

**Comment by SungMatt** [comment]
Fixed the typos in [516b22e](https://github.com/AY2324S1-CS2103-T16-1/tp/pull/133/commits/516b22e36f491d663ac7ad76c2a2133ff36f080c), fixes #85

**Review by kenvynKwek — APPROVED** [review]
LGTM

**Review by kenvynKwek — APPROVED** [review]
LGTM

**Comment by SungMatt** [comment]
Quick link fix.

**Review by kenvynKwek — APPROVED** [review]
LGTM

**Pull request merged**
