### PR TITLE
Add manager v1.3

### LINKED ISSUE #62: Implement employee hierarchy management feature
The current version of the ManagerHR application lacks the ability to efficiently represent the hierarchical structure of the company. To address this, we need to implement an employee hierarchy management system. This feature will allow users to visualize and manage the organizational structure, and make HR-related decisions more effectively.

### PR DESCRIPTION
**Pull request by XihuaZ**
Implemented a supervisor and subordinate relationship between employees.

NEW PREFIX:

`\r` for determining whether an employee is a `manager` or `subordinate`.
`\m` for including a supervisor who is in charge of the given employee.

Usage of PREFIXES:
To add a role, use either `\r subordinate` or `\r  manager`, and they are case insensitive.
To add a supervisor to be in charge of a given employee, use `\r Alex Yeoh`, where the given name must be exactly the same as an employee with `manager` role.

Note: 
- Multiple `\m` can be used if the given employee has more than 1 superior. 
- If the employee has no superior, `\m` can be omitted. `\m` can also be used for employees who are `manager`.

Constraints:
- Deletion of an employee is only possible when the given employee is no longer in charge of any employees.
- An employee cannot be added if he or she has a supervisor who is not yet stored within the app.
- An employee can only be in charge of others if he or she is a `manager`.
- An employee cannot switch role from `manager` to `subordinate` if he or she is still in charge of any employees.

Closes #62

### CODE REVIEW

**Comment by kenvynKwek** [comment]
question: whats the format for adding a manager ?
- is it by name eg. `m/John`
- or index eg. `m/1`

what about for multiple managers ?
- is it `m/John Mary` or something like `m/John m/Mary`

**Comment by XihuaZ** [comment]
I have update the the description. Thanks for letting me know!

**Review by kenvynKwek — APPROVED** [review]
LGTM

**Comment by XihuaZ** [comment]
closes #62

**Pull request merged**
